### PR TITLE
Clean task name config

### PR DESCRIPTION
**Pull request by vibdev**
adds a new `cleanTaskName` option for renaming the clean task to prevent task name conflicts

### CODE REVIEW

**Comment by PeredurOmega** [comment]
A possible improvement could be to make the 'clean' task dependent on the new cleaning task when the name is different from 'clean'.
What do you think ? How would that work with your use case ?

**Comment by vibdev** [comment]
I like that 👍

**Comment by PeredurOmega** [comment]
It should be the opposite, shouldn't it ? The clean task configured to depend on the nodeClean task

**Comment by vibdev** [comment]
Oh yeah, I see what your are saying. That makes sense, more automatic that way.

TBH I am not using your clean task because we have a nx monorepo and our javascript clean runs `nx run-many --target=clean --all` and then each package is responsible for its own clean up. But didn't want to introduce that can of worms here ha.

**Comment by vibdev** [comment]
Think I got it right way around now 👍

**Comment by vibdev** [comment]
just realized I didn't need to make my own DEFAULT name, I should just use `BasePlugin.CLEAN_TASK_NAME`

**Review by PeredurOmega — APPROVED** [review]
Looks great ! Thanks !

**Comment by PeredurOmega** [comment]
Released in 2.0.2 🚀

**Comment by vibdev** [comment]
It works! 🎉 Thank you so much. Pleasure working with you

**Pull request merged**
